# CircleCI v2.1 Config
version: 2.1
##
# orbs
#
# Orbs used in this pipeline
##
orbs:
  anchore: anchore/anchore-engine@1.9.0
  slack: circleci/slack@4.12.5 # Ref: https://github.com/mojaloop/ci-config/tree/main/slack-templates
  pr-tools: mojaloop/pr-tools@0.1.10 # Ref: https://github.com/mojaloop/ci-config/
  gh: circleci/github-cli@2.2.0

##
# Yaml anchors
#
##
defaults_environment: &defaults_environment
  MAIN_BRANCH_NAME: main

defaults_configure_git: &defaults_configure_git
  name: Configure git
  command: |
    git config user.email ${GIT_CI_EMAIL}
    git config user.name ${GIT_CI_USER}

defaults_license_scanner: &defaults_license_scanner
  name: Install and set up license-scanner
  command: |
    git clone https://github.com/mojaloop/license-scanner /tmp/license-scanner
    cd /tmp/license-scanner && make build default-files set-up

defaults_docker_Dependencies: &defaults_docker_Dependencies |
  sudo apt-get update
  sudo apt-get install -y --no-install-recommends \
    autoconf automake binutils build-essential ca-certificates coreutils curl \
    findutils git grep jq librdkafka-dev libssl-dev libtool openssh-client \
    python3 util-linux

## Default 'default-machine' executor dependencies
defaults_machine_Dependencies: &defaults_machine_Dependencies |
  ## Add Package Repos
  ## Ref: https://docs.confluent.io/platform/current/installation/installing_cp/deb-ubuntu.html#get-the-software
  wget -qO - https://packages.confluent.io/deb/7.4/archive.key | sudo apt-key add -
  sudo add-apt-repository -y "deb https://packages.confluent.io/clients/deb $(lsb_release -cs) main"

  ## Install deps
  sudo apt install -y librdkafka-dev curl bash musl-dev libsasl2-dev
  sudo ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

defaults_npm_auth: &defaults_npm_auth
  name: Update NPM registry auth token
  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

defaults_display_versions: &defaults_display_versions
  name: Display Versions
  command: |
    echo "node: $(node --version)"
    echo "npm: $(npm --version)"

##
# Executors
#
# CircleCI Executors
##
executors:
  default-docker:
    working_directory: &workingDirVar /home/circleci/project
    docker:
      # Primary container
      - image: cimg/node:24.18.0
      # Secondary containers for e2e tests
      - image: minio/minio:RELEASE.2023-07-21T21-12-44Z
        environment:
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        command: ["server", "/data"]
  default-machine:
    machine:
      image: ubuntu-2204:2023.04.2
      docker_layer_caching: true

jobs:
  setup:
    executor: default-docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "package-lock.json" }}
      - run: HUSKY=0 npm ci
      - save_cache:
          paths:
            - node_modules
          key: node_modules-cache-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .
  build:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run build
      - save_cache:
          paths:
            - packages
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .

  # build-local:
  #   executor: default-machine
  #   environment:
  #     <<: *defaults_environment
  #   steps:
  #     - checkout
  #     - run:
  #         <<: *defaults_configure_nvmrc
  #     - run:
  #         <<: *defaults_display_versions
  #     - run:
  #         name: Build Docker local image
  #         command: |
  #           source ~/.profile
  #           export DOCKER_NODE_VERSION="$NVMRC_VERSION-alpine"
  #           echo "export DOCKER_NODE_VERSION=$NVMRC_VERSION-alpine" >> $BASH_ENV
  #           echo "Building Docker image: ${DOCKER_ORG:-mojaloop}/$CIRCLE_PROJECT_REPONAME:local --build-arg NODE_VERSION=$DOCKER_NODE_VERSION"
  #           docker build -t ${DOCKER_ORG:-mojaloop}/$CIRCLE_PROJECT_REPONAME:local --build-arg NODE_VERSION=$DOCKER_NODE_VERSION .
  #     - run:
  #         name: Save docker image to workspace
  #         command: docker save -o /tmp/docker-image.tar ${DOCKER_ORG:-mojaloop}/$CIRCLE_PROJECT_REPONAME:local
  #     - persist_to_workspace:
  #         root: /tmp
  #         paths:
  #           - ./docker-image.tar

  lint-check-acquirer-backend:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run lint:check:backend

  lint-check-acquirer-frontend:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run lint:check:frontend

  lint-check-registry-oracle:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run lint:check:oracle

  type-check-acquirer-backend:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run type:check:backend

  type-check-acquirer-frontend:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run type:check:frontend

  type-check-registry-oracle:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run type:check:oracle

  dep-check-acquirer-backend:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run dep:check:backend

  dep-check-acquirer-frontend:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run dep:check:frontend

  dep-check-registry-oracle:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run: npm run dep:check:oracle

  tests-acquirer-frontend:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run:
          name: Execute frontend tests
          command: npm run test:unit:frontend

  tests-acquirer-backend:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run:
          name: Execute backend tests
          command: npm run acquirer-backend:test

  tests-oracle:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run:
          name: Execute registry oracle tests
          command: npm run oracle:test

  publish:
    executor: default-machine
    steps:
      - attach_workspace:
          at: *workingDirVar
      - run:
          <<: *defaults_configure_git
      - run:
          name: Add github.com to known hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          <<: *defaults_npm_auth
      - run:
          name: Configure NPM registry
          command: npm config set registry https://registry.npmjs.org/
      - run:
          name: Detect changes, publishing npm and publish docker images
          no_output_timeout: 30m
          command: chmod +x .circleci/*.sh && .circleci/publish.sh

  vulnerability-check:
    executor: default-docker
    environment:
      <<: *defaults_environment
    steps:
      - run:
          name: Install general dependencies
          command: *defaults_docker_Dependencies
      - checkout
      - run:
          <<: *defaults_display_versions
      - restore_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Create dir for test results
          command: mkdir -p ./audit/results
      - run:
          name: Check for new npm vulnerabilities
          command: npm run audit:check -- -o json > ./audit/results/auditResults.json
      - store_artifacts:
          path: ./audit/results
          destination: audit

  audit-licenses:
    executor: default-docker
    environment:
      <<: *defaults_environment
    steps:
      - run:
          name: Install general dependencies
          command: *defaults_docker_Dependencies
      - run:
          <<: *defaults_license_scanner
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run the license-scanner
          command: cd /tmp/license-scanner && pathToRepo=$CIRCLE_WORKING_DIRECTORY make run
      - store_artifacts:
          path: /tmp/license-scanner/results
          destination: licenses

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - pr-tools/pr-title-check:
          context: org-global
      - setup:
          context: org-global
      - build:
          context: org-global
          requires:
            - setup
      - vulnerability-check:
          context: org-global
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
      - audit-licenses:
          context: org-global
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /feature*/
                - /bugfix*/

      - lint-check-acquirer-backend:
          context: org-global
          requires:
            - setup

      - lint-check-acquirer-frontend:
          context: org-global
          requires:
            - setup

      - lint-check-registry-oracle:
          context: org-global
          requires:
            - setup

      - type-check-acquirer-backend:
          context: org-global
          requires:
            - setup

      - type-check-acquirer-frontend:
          context: org-global
          requires:
            - setup

      - type-check-registry-oracle:
          context: org-global
          requires:
            - setup

      - tests-acquirer-backend:
          context: org-global
          requires:
            - setup

      - tests-oracle:
          context: org-global
          requires:
            - setup

      - tests-acquirer-frontend:
          context: org-global
          requires:
            - setup

      - publish:
          context: org-global
          filters:
            branches:
              only: main
          requires:
            - setup
            - build
            - tests-acquirer-backend
            - tests-oracle
            - tests-acquirer-frontend

            - lint-check-acquirer-backend
            - lint-check-acquirer-frontend
            - lint-check-registry-oracle

            - type-check-acquirer-backend
            - type-check-acquirer-frontend
            - type-check-registry-oracle
