apiVersion: v2
name: merchant-registry
description: Merchant registry, acquirer portal, and Mojaloop registry oracle
type: application
version: 1.1.0
appVersion: "1.1.6"
kubeVersion: ">=1.24.0-0"
home: https://github.com/ThitsaX/merchant-registry-svc
sources:
  - https://github.com/ThitsaX/merchant-registry-svc
maintainers:
  - name: ThitsaX
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: acquirer-backend
      image: ghcr.io/thitsax/merchant-acquirer-backend:v1.1.6
    - name: acquirer-frontend
      image: ghcr.io/thitsax/merchant-acquirer-frontend:v1.1.6
    - name: registry-oracle
      image: ghcr.io/thitsax/merchant-registry-oracle:v1.1.6
